### ISSUE TITLE
vague errors when go-ping does not exist

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-collector#14]
was getting this in dev stack:

```
[2015-06-25 22:27:38.852] [INFO] PID:23 - starting up go-ping server
[2015-06-25 22:27:38.855] [INFO] PID:23 - launching worker process.
[2015-06-25 22:27:38.857] [INFO] PID:23 - launching worker process.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

i noticed `go-ping` binary did not exist, but this error should be clearer

**Comment by ctdk** [comment]
I had pulled go-ping out of the repo so that you can just build it locally, incidentally. We'll either need to add that build step, or have the dev stack use the package.

**Comment by ctdk** [comment]
(that said the collector errors are really vague indeed)
