### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-collector#30]
```
[2015-10-13 16:19:35.589] [INFO] PID:49 - check delay is 73.699462890625ms
[2015-10-13 16:19:35.592] [INFO] PID:49 - got serviceUpdate message for service: 17
[2015-10-13 16:19:35.862] [INFO] PID:51 - got serviceUpdate message for service: 18
[2015-10-13 16:19:36.725] [WARN] PID:49 - check delay is 163.505859375ms. Skipping check

/opt/raintank/raintank-collector/serviceManager.js:217
      runNext(service.id);
                     ^
TypeError: Cannot read property 'id' of undefined
    at run (/opt/raintank/raintank-collector/serviceManager.js:217:22)
    at null._onTimeout (/opt/raintank/raintank-collector/serviceManager.js:364:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
[2015-10-13 16:19:36.758] [ERROR] PID:27 - worker 49 died, restarting.
[2015-10-13 16:19:36.758] [INFO] PID:27 - 3 restarts in last 2 minutes.
[2015-10-13 16:19:37.574] [INFO] PID:61 - connected to socket.io server
[2015-10-13 16:19:38.773] [DEBUG] PID:51 - initializing metric:  dns.ok_state
[2015-10-13 16:19:38.773] [DEBUG] PID:51 - initializing metric:  dns.warn_state
[2015-10-13 16:19:38.773] [DEBUG] PID:51 - initializing metric:  dns.error_state
[2015-10-13 16:19:38.773] [INFO] PID:51 - got serviceUpdate message for service: 20
[2015-10-13 16:19:38.773] [DEBUG] PID:51 - scheduling new service 20
```

**Comment by Dieterbe** [comment]
looks like it should be serviceId
