### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'timer' in undefined

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-collector#32]
seen in devstack after adding a new endpoint

```
[2015-11-20 07:16:08.490] [INFO] PID:118 - got serviceUpdate message for service: 2
[2015-11-20 07:16:08.490] [DEBUG] PID:118 - removing check 2 from run queue

/opt/raintank/raintank-collector/serviceManager.js:201
    if ('timer' in serviceCache[id]) {
                               ^
TypeError: Cannot use 'in' operator to search for 'timer' in undefined
    at _checkDelete (/opt/raintank/raintank-collector/serviceManager.js:201:32)
    at serviceUpdate (/opt/raintank/raintank-collector/serviceManager.js:157:17)
    at Socket.<anonymous> (/opt/raintank/raintank-collector/serviceManager.js:68:9)
    at Socket.Emitter.emit (/opt/raintank/raintank-collector/node_modules/socket.io-client/node_modules/component-emitter/index.js:134:20)
    at Socket.onevent (/opt/raintank/raintank-collector/node_modules/socket.io-client/lib/socket.js:254:10)
    at Socket.onpacket (/opt/raintank/raintank-collector/node_modules/socket.io-client/lib/socket.js:212:12)
    at Manager.<anonymous> (/opt/raintank/raintank-collector/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/opt/raintank/raintank-collector/node_modules/socket.io-client/node_modules/component-emitter/index.js:134:20)
    at Manager.ondecoded (/opt/raintank/raintank-collector/node_modules/socket.io-client/lib/manager.js:301:8)
    at Decoder.<anonymous> (/opt/raintank/raintank-collector/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
[2015-11-20 07:16:08.494] [ERROR] PID:110 - worker 118 died, restarting.
[2015-11-20 07:16:08.494] [INFO] PID:110 - 1 restarts in last 2 minutes.
[2015-11-20 07:16:08.500] [DEBUG] PID:117 - refreshing checks: check count: 3
```

**Comment by Dieterbe** [comment]
@woodsaj if that fixes it can you please merge it into master
